echo "ProjectId,ProjectName,InterconnectName,Location,OperationalStatus,AdminEnabled"                                                                                                                                                        
for PROJECT in $(\                                                                                                                                                                                                                         
        gcloud projects list \                                                                                                                                                                                                             
        --format="value(projectId)")                                                                                                                                                                                                       
do                                                                                                                                                                                                                                         
        PROJECTNAME=$(gcloud projects list --format="csv[no-heading](name)" --filter="projectId=${PROJECT}")                                                                                                                               
        gcloud compute interconnects list --project=${PROJECT} --format="csv[no-heading](NAME,LOCATION,OPERATIONAL_STATUS,ADMIN_ENABLED)" > ./temp/interconnects.txt                                                                                                   
                                                                                                                                                                                                                                           
        cat ./temp/interconnects.txt | while read LINE                                                                                                                                                                                   
        do                                                                                                                                                                                                                                 
                echo "${PROJECT},${PROJECTNAME},${LINE}"                                                                                                                                                                                   
        done                                                                                                                                                                                                                               
done
