echo "ProjectId,ProjectName,SubscriptionName,topic,ackDeadlineSeconds,deadLetterPolicy,deadLetterPolicy.deadLetterTopic,deadLetterPolicy.maxDeliveryAttempts,expirationPolicy,messageRetentionDuration,pushConfig.pushEndpoint"                                                                                                                                                   
for PROJECT in $(\                                                                                                                                                                                                                         
        gcloud projects list \                                                                                                                                                                                                             
        --format="value(projectId)")                                                                                                                                                                                                       
do                                                                                                                                                                                                                                         
        PROJECTNAME=$(gcloud projects list --format="csv[no-heading](name)" --filter="projectId=${PROJECT}")                                                                                                                               
        gcloud pubsub subscriptions list --project=${PROJECT} --format="csv[no-heading](name,topic,ackDeadlineSeconds,deadLetterPolicy,deadLetterPolicy.deadLetterTopic,deadLetterPolicy.maxDeliveryAttempts,expirationPolicy,messageRetentionDuration,pushConfig.pushEndpoint)" --quiet > ./temp/pubsub.txt                                                                                                                                                                                                         
        cat ./temp/pubsub.txt | while read LINE                                                                                                                                                                                   
        do                                                                                                                                                                                                                                 
                echo "${PROJECT},${PROJECTNAME},${LINE}"                                                                                                                                                                                   
        done                                                                                                                                                                                                                               
done

