echo "ProjectId,ProjectName,InterconnectName,Location,OperationalStatus,AdminEnabled"        
#get each projectId                                                                                                                                                
for PROJECT in $(\                                                                                                                                                                                                                         
        gcloud projects list \                                                                                                                                                                                                             
        --format="value(projectId)")                                                                                                                                                                                                       
do                                                                                                                                                                                                                                         
        PROJECTNAME=$(gcloud projects list --format="csv[no-heading](name)" --filter="projectId=${PROJECT}")    #get projectName                                                                                                                           
        gcloud compute interconnects list --project=${PROJECT} --format="csv[no-heading](NAME,LOCATION,OPERATIONAL_STATUS,ADMIN_ENABLED)" > ./temp/interconnects.txt  #get inteconnects details and store in temp folder                                                                                                 
                                                                                                                                                                                                                                           
        cat ./temp/interconnects.txt | while read LINE                                                                                                                                                                                   
        do                                                                                                                                                                                                                                 
                echo "${PROJECT},${PROJECTNAME},${LINE}"     #print projectId,ProjectName and inerconnects details stored in temp folder                                                                                                                                                                              
        done                                                                                                                                                                                                                               
done
