echo "ProjectId,ProjectName,Name,Address,PrefixLength,Type,Purpose,Network,Region,Subnet,Status"                                                                                                                                                                     
for PROJECT in $(\                                                                                                                                                                                                                         
        gcloud projects list \                                                                                                                                                                                                             
        --format="value(projectId)")                                                                                                                                                                                                       
do                                                                                                                                                                                                                                         
        PROJECTNAME=$(gcloud projects list --format="csv[no-heading](name)" --filter="projectId=${PROJECT}")                                                                                                                               
        gcloud compute address list --format="csv[no-heading](NAME,ADDRESS,prefixLength,TYPE,PURPOSE,NETWORK,REGION,SUBNET,STATUS)" --project=${PROJECT} > ./temp/ip_address.txt                                                                                                     
                                                                                                                                                                                                                                           
        cat ./temp/ip_address.txt | while read LINE                                                                                                                                                                                   
        do                                                                                                                                                                                                                                 
                echo "${PROJECT},${PROJECTNAME},${LINE}"                                                                                                                                                                                   
        done                                                                                                                                                                                                                               
done
